# Generated by Django 4.2.30 on 2026-07-03 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('papers', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPaperSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('notes', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_papers', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_schedules', to='profiles.profile')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_schedules', to='papers.paper')),
            ],
            options={
                'db_table': 'club_paper_schedule',
            },
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='schedule.clubpaperschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='profiles.profile')),
            ],
            options={
                'db_table': 'reading_logs',
                'indexes': [models.Index(fields=['user', 'read_at'], name='reading_logs_user_read_idx'), models.Index(fields=['schedule'], name='reading_logs_schedule_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='readinglog',
            constraint=models.UniqueConstraint(fields=('schedule', 'user'), name='reading_logs_schedule_user_unique'),
        ),
        migrations.AddIndex(
            model_name='clubpaperschedule',
            index=models.Index(fields=['paper'], name='club_paper_sched_paper_idx'),
        ),
        migrations.AddIndex(
            model_name='clubpaperschedule',
            index=models.Index(fields=['created_by'], name='club_paper_sched_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubpaperschedule',
            constraint=models.UniqueConstraint(fields=('club', 'week_start'), name='club_paper_schedule_club_week_unique'),
        ),
        migrations.AddConstraint(
            model_name='clubpaperschedule',
            constraint=models.CheckConstraint(check=models.Q(('week_start__week_day', 2)), name='club_paper_schedule_week_start_monday_check'),
        ),
    ]
