# Generated by Django 4.2.30 on 2026-07-03 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_personalpaper"),
        ("profiles", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pages_read",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "personal_paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to="papers.personalpaper",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to="schedule.clubpaperschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "reading_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "logged_at"],
                        name="read_sess_user_logged_idx",
                    ),
                    models.Index(
                        fields=["schedule"],
                        name="read_sess_schedule_idx",
                    ),
                    models.Index(
                        fields=["personal_paper"],
                        name="read_sess_personal_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="readingsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("schedule__isnull", False),
                        ("personal_paper__isnull", True),
                    ),
                    models.Q(
                        ("schedule__isnull", True),
                        ("personal_paper__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="read_sess_one_context_chk",
            ),
        ),
    ]
