# Generated by Django 4.2.30 on 2026-07-03

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid


def populate_schedule_statuses(apps, _schema_editor):
    ReadingLog = apps.get_model("schedule", "ReadingLog")
    ReadingSession = apps.get_model("schedule", "ReadingSession")
    SchedulePaperStatus = apps.get_model("schedule", "SchedulePaperStatus")

    for log in ReadingLog.objects.all():
        SchedulePaperStatus.objects.update_or_create(
            schedule_id=log.schedule_id,
            user_id=log.user_id,
            defaults={
                "status": "read",
                "read_at": log.read_at or timezone.now(),
            },
        )

    session_pairs = (
        ReadingSession.objects.filter(schedule__isnull=False)
        .values_list("schedule_id", "user_id")
        .distinct()
    )
    for schedule_id, user_id in session_pairs:
        SchedulePaperStatus.objects.get_or_create(
            schedule_id=schedule_id,
            user_id=user_id,
            defaults={"status": "reading"},
        )


def clear_schedule_statuses(apps, _schema_editor):
    SchedulePaperStatus = apps.get_model("schedule", "SchedulePaperStatus")
    SchedulePaperStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("schedule", "0002_readingsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulePaperStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("reading", "Reading"),
                            ("on_hold", "On hold"),
                            ("dropped", "Dropped"),
                            ("read", "Read"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="schedule.clubpaperschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_paper_statuses",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_paper_statuses",
                "indexes": [
                    models.Index(fields=["user", "status"], name="sched_status_user_idx"),
                    models.Index(
                        fields=["schedule", "status"],
                        name="sched_status_sched_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schedulepaperstatus",
            constraint=models.UniqueConstraint(
                fields=("schedule", "user"),
                name="sched_paper_status_unique",
            ),
        ),
        migrations.RunPython(populate_schedule_statuses, clear_schedule_statuses),
    ]
