# Generated by Django 4.2.30 on 2026-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedulepaperstatus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubpaperschedule',
            name='club_paper_schedule_club_week_unique',
        ),
        migrations.RemoveConstraint(
            model_name='clubpaperschedule',
            name='club_paper_schedule_week_start_monday_check',
        ),
        migrations.AlterField(
            model_name='clubpaperschedule',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
