# Generated by Django 4.2.30 on 2026-07-03 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clubs', to='profiles.profile')),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='ClubInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_invites', to='profiles.profile')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='clubs.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invites', to='profiles.profile')),
            ],
            options={
                'db_table': 'club_invites',
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='profiles.profile')),
            ],
            options={
                'db_table': 'club_members',
                'indexes': [models.Index(fields=['user', 'club'], name='club_members_user_club_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='club_members_club_user_pk'),
        ),
        migrations.AddIndex(
            model_name='clubinvite',
            index=models.Index(fields=['club', 'status'], name='club_invites_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clubinvite',
            index=models.Index(fields=['created_by'], name='club_invites_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='clubinvite',
            index=models.Index(fields=['accepted_by'], name='club_invites_accepted_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('club',), name='club_invites_one_pending_per_club_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubinvite',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('created_at')), _connector='OR'), name='club_invites_expires_after_created'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['created_by'], name='clubs_created_by_idx'),
        ),
    ]
