# Generated by Django 4.2.30 on 2026-07-03 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('papers', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('highlight', 'Highlight'), ('question', 'Question'), ('explanation', 'Explanation'), ('note', 'Note')], max_length=24)),
                ('page_number', models.PositiveIntegerField()),
                ('position', models.JSONField()),
                ('quote', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('body', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('color', models.CharField(default='#facc15', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_annotations', to='profiles.profile')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='papers.paper')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='schedule.clubpaperschedule')),
            ],
            options={
                'db_table': 'paper_annotations',
            },
        ),
        migrations.CreateModel(
            name='PaperAnnotationReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='annotations.paperannotation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_replies', to='profiles.profile')),
            ],
            options={
                'db_table': 'paper_annotation_replies',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['annotation', 'created_at'], name='ann_reply_created_active_idx'), models.Index(fields=['author'], name='ann_reply_author_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paperannotation',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['schedule', 'paper', 'page_number', 'created_at'], name='paper_ann_page_active_idx'),
        ),
        migrations.AddIndex(
            model_name='paperannotation',
            index=models.Index(fields=['author'], name='paper_ann_author_idx'),
        ),
    ]
