# Generated by Django 4.2.30 on 2026-07-03 11:47

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('arxiv', 'arXiv'), ('manual', 'Manual')], max_length=16)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('arxiv_id', models.TextField(blank=True, null=True)),
                ('abstract_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('pdf_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('external_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(condition=models.Q(('arxiv_id__isnull', False)), fields=('arxiv_id',), name='papers_arxiv_id_unique_idx'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_type', 'arxiv'), ('arxiv_id__isnull', False), ('abstract_url__isnull', False), ('pdf_url__isnull', False), ('external_url__isnull', True)), models.Q(('source_type', 'manual'), ('external_url__isnull', False), ('arxiv_id__isnull', True), ('abstract_url__isnull', True), ('pdf_url__isnull', True)), _connector='OR'), name='papers_source_metadata_check'),
        ),
    ]
