# Generated by Django 4.2.30 on 2026-07-03 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_saves",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_papers",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "personal_papers",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="pers_paper_user_created_idx",
                    ),
                    models.Index(
                        fields=["user", "read_at"],
                        name="pers_paper_user_read_idx",
                    ),
                    models.Index(fields=["paper"], name="pers_paper_paper_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="personalpaper",
            constraint=models.UniqueConstraint(
                fields=("user", "paper"),
                name="pers_paper_user_paper_unique",
            ),
        ),
    ]
