# Generated by Django 4.2.30 on 2026-07-03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_personalpaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
