# Generated by Django 4.2.30 on 2026-07-03

from django.db import migrations, models


def populate_personal_paper_status(apps, _schema_editor):
    PersonalPaper = apps.get_model("papers", "PersonalPaper")
    ReadingSession = apps.get_model("schedule", "ReadingSession")

    PersonalPaper.objects.filter(read_at__isnull=False).update(status="read")

    personal_paper_ids_with_sessions = (
        ReadingSession.objects.filter(
            personal_paper__isnull=False,
            personal_paper__read_at__isnull=True,
        )
        .values_list("personal_paper_id", flat=True)
        .distinct()
    )
    PersonalPaper.objects.filter(id__in=personal_paper_ids_with_sessions).update(
        status="reading",
    )


def clear_personal_paper_status(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_paper_page_count"),
        ("schedule", "0002_readingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalpaper",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("reading", "Reading"),
                    ("on_hold", "On hold"),
                    ("dropped", "Dropped"),
                    ("read", "Read"),
                ],
                default="planned",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="personalpaper",
            index=models.Index(
                fields=["user", "status"],
                name="pers_paper_user_status_idx",
            ),
        ),
        migrations.RunPython(
            populate_personal_paper_status,
            clear_personal_paper_status,
        ),
    ]
