# Generated by Django 4.2.30 on 2026-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_personalpaper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpaper',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='personalpaper',
            index=models.Index(fields=['user', 'deadline'], name='pers_paper_user_deadline_idx'),
        ),
    ]
