# Generated by Django 4.2.30 on 2026-07-03 11:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=120)),
                ('avatar_id', models.CharField(choices=[('bookworm', 'Bookworm'), ('cat', 'Cat'), ('dog', 'Dog'), ('wizard', 'Wizard'), ('owl', 'Owl'), ('robot', 'Robot')], default='bookworm', max_length=24)),
                ('avatar_color', models.CharField(default='#65a30d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')])),
                ('bio', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
