/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as InvitesTokenRouteImport } from './routes/invites.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppClubsIndexRouteImport } from './routes/app.clubs.index'
import { Route as AppPersonalPapersPersonalPaperIdRouteImport } from './routes/app.personal-papers.$personalPaperId'
import { Route as AppPapersScheduleIdRouteImport } from './routes/app.papers.$scheduleId'
import { Route as AppClubsNewRouteImport } from './routes/app.clubs.new'
import { Route as AppClubsClubIdRouteImport } from './routes/app.clubs.$clubId'
import { Route as AppClubsClubIdIndexRouteImport } from './routes/app.clubs.$clubId.index'
import { Route as AppClubsClubIdMembersRouteImport } from './routes/app.clubs.$clubId.members'
import { Route as AppClubsClubIdScheduleIndexRouteImport } from './routes/app.clubs.$clubId.schedule.index'
import { Route as AppClubsClubIdScheduleScheduleIdRouteImport } from './routes/app.clubs.$clubId.schedule.$scheduleId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InvitesTokenRoute = InvitesTokenRouteImport.update({
  id: '/invites/$token',
  path: '/invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsIndexRoute = AppClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalPapersPersonalPaperIdRoute =
  AppPersonalPapersPersonalPaperIdRouteImport.update({
    id: '/personal-papers/$personalPaperId',
    path: '/personal-papers/$personalPaperId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPapersScheduleIdRoute = AppPapersScheduleIdRouteImport.update({
  id: '/papers/$scheduleId',
  path: '/papers/$scheduleId',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsNewRoute = AppClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsClubIdRoute = AppClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsClubIdIndexRoute = AppClubsClubIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClubsClubIdRoute,
} as any)
const AppClubsClubIdMembersRoute = AppClubsClubIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppClubsClubIdRoute,
} as any)
const AppClubsClubIdScheduleIndexRoute =
  AppClubsClubIdScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AppClubsClubIdRoute,
  } as any)
const AppClubsClubIdScheduleScheduleIdRoute =
  AppClubsClubIdScheduleScheduleIdRouteImport.update({
    id: '/schedule/$scheduleId',
    path: '/schedule/$scheduleId',
    getParentRoute: () => AppClubsClubIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRouteWithChildren
  '/app/clubs/new': typeof AppClubsNewRoute
  '/app/papers/$scheduleId': typeof AppPapersScheduleIdRoute
  '/app/personal-papers/$personalPaperId': typeof AppPersonalPapersPersonalPaperIdRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/clubs/$clubId/members': typeof AppClubsClubIdMembersRoute
  '/app/clubs/$clubId/': typeof AppClubsClubIdIndexRoute
  '/app/clubs/$clubId/schedule/$scheduleId': typeof AppClubsClubIdScheduleScheduleIdRoute
  '/app/clubs/$clubId/schedule/': typeof AppClubsClubIdScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/app': typeof AppIndexRoute
  '/app/clubs/new': typeof AppClubsNewRoute
  '/app/papers/$scheduleId': typeof AppPapersScheduleIdRoute
  '/app/personal-papers/$personalPaperId': typeof AppPersonalPapersPersonalPaperIdRoute
  '/app/clubs': typeof AppClubsIndexRoute
  '/app/clubs/$clubId/members': typeof AppClubsClubIdMembersRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdIndexRoute
  '/app/clubs/$clubId/schedule/$scheduleId': typeof AppClubsClubIdScheduleScheduleIdRoute
  '/app/clubs/$clubId/schedule': typeof AppClubsClubIdScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invites/$token': typeof InvitesTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/clubs/$clubId': typeof AppClubsClubIdRouteWithChildren
  '/app/clubs/new': typeof AppClubsNewRoute
  '/app/papers/$scheduleId': typeof AppPapersScheduleIdRoute
  '/app/personal-papers/$personalPaperId': typeof AppPersonalPapersPersonalPaperIdRoute
  '/app/clubs/': typeof AppClubsIndexRoute
  '/app/clubs/$clubId/members': typeof AppClubsClubIdMembersRoute
  '/app/clubs/$clubId/': typeof AppClubsClubIdIndexRoute
  '/app/clubs/$clubId/schedule/$scheduleId': typeof AppClubsClubIdScheduleScheduleIdRoute
  '/app/clubs/$clubId/schedule/': typeof AppClubsClubIdScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/profile'
    | '/auth/callback'
    | '/invites/$token'
    | '/app/'
    | '/app/clubs/$clubId'
    | '/app/clubs/new'
    | '/app/papers/$scheduleId'
    | '/app/personal-papers/$personalPaperId'
    | '/app/clubs/'
    | '/app/clubs/$clubId/members'
    | '/app/clubs/$clubId/'
    | '/app/clubs/$clubId/schedule/$scheduleId'
    | '/app/clubs/$clubId/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/profile'
    | '/auth/callback'
    | '/invites/$token'
    | '/app'
    | '/app/clubs/new'
    | '/app/papers/$scheduleId'
    | '/app/personal-papers/$personalPaperId'
    | '/app/clubs'
    | '/app/clubs/$clubId/members'
    | '/app/clubs/$clubId'
    | '/app/clubs/$clubId/schedule/$scheduleId'
    | '/app/clubs/$clubId/schedule'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/profile'
    | '/auth/callback'
    | '/invites/$token'
    | '/app/'
    | '/app/clubs/$clubId'
    | '/app/clubs/new'
    | '/app/papers/$scheduleId'
    | '/app/personal-papers/$personalPaperId'
    | '/app/clubs/'
    | '/app/clubs/$clubId/members'
    | '/app/clubs/$clubId/'
    | '/app/clubs/$clubId/schedule/$scheduleId'
    | '/app/clubs/$clubId/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InvitesTokenRoute: typeof InvitesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invites/$token': {
      id: '/invites/$token'
      path: '/invites/$token'
      fullPath: '/invites/$token'
      preLoaderRoute: typeof InvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/': {
      id: '/app/clubs/'
      path: '/clubs'
      fullPath: '/app/clubs/'
      preLoaderRoute: typeof AppClubsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/personal-papers/$personalPaperId': {
      id: '/app/personal-papers/$personalPaperId'
      path: '/personal-papers/$personalPaperId'
      fullPath: '/app/personal-papers/$personalPaperId'
      preLoaderRoute: typeof AppPersonalPapersPersonalPaperIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/papers/$scheduleId': {
      id: '/app/papers/$scheduleId'
      path: '/papers/$scheduleId'
      fullPath: '/app/papers/$scheduleId'
      preLoaderRoute: typeof AppPapersScheduleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/new': {
      id: '/app/clubs/new'
      path: '/clubs/new'
      fullPath: '/app/clubs/new'
      preLoaderRoute: typeof AppClubsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/$clubId': {
      id: '/app/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/app/clubs/$clubId'
      preLoaderRoute: typeof AppClubsClubIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs/$clubId/': {
      id: '/app/clubs/$clubId/'
      path: '/'
      fullPath: '/app/clubs/$clubId/'
      preLoaderRoute: typeof AppClubsClubIdIndexRouteImport
      parentRoute: typeof AppClubsClubIdRoute
    }
    '/app/clubs/$clubId/members': {
      id: '/app/clubs/$clubId/members'
      path: '/members'
      fullPath: '/app/clubs/$clubId/members'
      preLoaderRoute: typeof AppClubsClubIdMembersRouteImport
      parentRoute: typeof AppClubsClubIdRoute
    }
    '/app/clubs/$clubId/schedule/': {
      id: '/app/clubs/$clubId/schedule/'
      path: '/schedule'
      fullPath: '/app/clubs/$clubId/schedule/'
      preLoaderRoute: typeof AppClubsClubIdScheduleIndexRouteImport
      parentRoute: typeof AppClubsClubIdRoute
    }
    '/app/clubs/$clubId/schedule/$scheduleId': {
      id: '/app/clubs/$clubId/schedule/$scheduleId'
      path: '/schedule/$scheduleId'
      fullPath: '/app/clubs/$clubId/schedule/$scheduleId'
      preLoaderRoute: typeof AppClubsClubIdScheduleScheduleIdRouteImport
      parentRoute: typeof AppClubsClubIdRoute
    }
  }
}

interface AppClubsClubIdRouteChildren {
  AppClubsClubIdMembersRoute: typeof AppClubsClubIdMembersRoute
  AppClubsClubIdIndexRoute: typeof AppClubsClubIdIndexRoute
  AppClubsClubIdScheduleScheduleIdRoute: typeof AppClubsClubIdScheduleScheduleIdRoute
  AppClubsClubIdScheduleIndexRoute: typeof AppClubsClubIdScheduleIndexRoute
}

const AppClubsClubIdRouteChildren: AppClubsClubIdRouteChildren = {
  AppClubsClubIdMembersRoute: AppClubsClubIdMembersRoute,
  AppClubsClubIdIndexRoute: AppClubsClubIdIndexRoute,
  AppClubsClubIdScheduleScheduleIdRoute: AppClubsClubIdScheduleScheduleIdRoute,
  AppClubsClubIdScheduleIndexRoute: AppClubsClubIdScheduleIndexRoute,
}

const AppClubsClubIdRouteWithChildren = AppClubsClubIdRoute._addFileChildren(
  AppClubsClubIdRouteChildren,
)

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClubsClubIdRoute: typeof AppClubsClubIdRouteWithChildren
  AppClubsNewRoute: typeof AppClubsNewRoute
  AppPapersScheduleIdRoute: typeof AppPapersScheduleIdRoute
  AppPersonalPapersPersonalPaperIdRoute: typeof AppPersonalPapersPersonalPaperIdRoute
  AppClubsIndexRoute: typeof AppClubsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppClubsClubIdRoute: AppClubsClubIdRouteWithChildren,
  AppClubsNewRoute: AppClubsNewRoute,
  AppPapersScheduleIdRoute: AppPapersScheduleIdRoute,
  AppPersonalPapersPersonalPaperIdRoute: AppPersonalPapersPersonalPaperIdRoute,
  AppClubsIndexRoute: AppClubsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InvitesTokenRoute: InvitesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
