# Generated by Django 4.2.30 on 2026-07-03 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.profile')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schedule.clubpaperschedule')),
            ],
            options={
                'db_table': 'comments',
                'indexes': [models.Index(fields=['author'], name='comments_author_id_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['schedule', 'created_at'], name='comments_schedule_active_idx')],
            },
        ),
    ]
